name: VRT Workflow

on:
  push:


jobs:
  compare:
    name: Compare Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Run VRT compare
        run: |
          vrt compare

      - name: Upload difference images as artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: vrt-differences
          path: vrt-difference/

  approve:
    name: Approve Images
    runs-on: ubuntu-latest
    needs: compare
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Run VRT approve
        run: |
          vrt approve

      - name: Commit and push approved images
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add vrt-expected/
          git commit -m "Approve VRT images"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
